#!/usr/bin/env bash
# Install nginx on your web-01 server

# install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# configure server
sudo echo "Hello World!" | sudo tee /var/www/html/index.html

# start server
sudo service nginx start
