#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the
# string Ceci n'est pas une page.

# Requirements:
#     - The page must return an HTTP 404 error code
#     - The page must contain the string Ceci n'est pas une page
#     - Using what you did with 3-redirection, write 4-not_found_page_404 so
#       that it configures a brand new Ubuntu machine to the requirements asked
#       in this task

apt-get -y update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/FREDRICKKYEKI permanent;/" /etc/nginx/sites-available/default

service nginx start
