#!/usr/bin/env bash
# script that configures HAproxy in a load balancer with round robin
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 938-web-01 35.231.33.237:80 check\n\tserver 938-web-02 34.74.155.163:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
