#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it. 
mysqldump -u root --password="$1" --all-databases > backup.sql
file=$(date +'%d-%m-%Y')
tar cfvz "$file".tar.gz backup.sql
