#!/usr/bin/env bash
# Script with the minimum number of commands to automate your fix (shorter).
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /run/nginx.pid)"
