#!/usr/bin/env bash
# script that configures the container to run as nginx user
sudo chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
pkill -9 apache
sudo service nginx restart
